openapi: 3.0.3

info:
  title: Meu API de Gerenciamento de Clientes e Produtos 
  description: Esse é o meu primeiro modelo de documentação, afim de descrever o que cada uma das minhas APIS estão fazendo em meu codigo
  version: 0.1.9

servers:
  - url: http://localhost:8507
paths:
  /produto:
    get:
      summary: Obter a lista de produtos
      responses:
        '200':
          description: Lista de produtos retornada com sucesso

    post:
      summary: Criar um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
                preco:
                  type: number
              required:
                - nome
                - preco
      responses:
        '200':
          description: Produto criado com sucesso
        '406':
          description: 'Nome e preço deve ser informado'

  /produto/{id}:
    get:
      summary: Obter informações de um produto pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do produto
          schema:
            type: string
      responses:
        '200':
          description: Informações do produto retornadas com sucesso
        '404': 
          description: Não Encontrado
          
    put:
      summary: Atualizar um produto existente
      parameters:
        - in: path
          name: id
          required: true
          description: ID do produto a ser atualizado
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
                preco:
                  type: number
      responses:
        '200':
          description: Produto atualizado com sucesso
        '404': 
          description: Não Encontrado

    delete:
      summary: Deletar um produto pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do produto a ser deletado
          schema:
            type: string
      responses:
        '200':
          description: Produto deletado com sucesso
        '404': 
          description: Não Encontrado

  /clientes:
    get:
      summary: Obter a lista de clientes
      responses:
        '200':
          description: Lista de clientes retornada com sucesso
    post:
      summary: Criar um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                  format: email
                senha:
                  type: string
              required:
                - nome
                - email
                - senha
      responses:
        '204':
          description: Cliente criado com sucesso
        '406':
          description: 'Nome, email e senha devem ser informados'
        '409':
          description: 'Email já cadastrado'

  /clientes/{id}:
    get:
      summary: Obter informações de um cliente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente
          schema:
            type: string
      responses:
        '200':
          description: Informações do cliente retornadas com sucesso
        '404': 
          description: Não Encontrado
          
    put:
      summary: Atualizar um cliente existente
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente a ser atualizado
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
              required:
                - nome
      responses:
        '204':
          description: Cliente atualizado com sucesso
        '404': 
          description: Não Encontrado

    delete:
      summary: Deletar um cliente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do cliente a ser deletado
          schema:
            type: string
      responses:
        '204':
          description: Cliente deletado com sucesso
        '404': 
          description: Não Encontrado

  /auth/login:
    post:
      summary: Realizar login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                senha:
                  type: string
              required:
                - email
                - senha
      responses:
        '200':
          description: Login realizado com sucesso
        '401':
          description: Credenciais inválidas
        '404': 
          description: Não Encontrado
